packages:
  - packages/common
  - packages/pdf-lib
  - packages/converter
  - packages/schemas
  - packages/generator
  - packages/manipulator
  - packages/ui
  - playground

onlyBuiltDependencies:
  - canvas
  - unrs-resolver
